# Generated by Django 4.2 on 2023-05-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_entrepreneur', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=15)),
                ('upazilla', models.CharField(max_length=15)),
                ('village', models.CharField(max_length=15)),
                ('mobile', models.IntegerField()),
                ('image', models.ImageField(default='default.png', upload_to='entrepreneur_pics')),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
