# Generated by Django 4.2 on 2023-05-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_cow', models.CharField(blank=True, max_length=30)),
                ('purchase_date', models.DateField()),
                ('breed', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=15)),
                ('weight', models.IntegerField(null=True)),
                ('date_of_birth', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='media/images')),
                ('owner', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
