# Generated by Django 4.2 on 2023-05-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0003_duplicate_cow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='breed',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cow',
            name='color',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cow',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='cow',
            name='name_of_cow',
            field=models.CharField(max_length=30),
        ),
    ]
