# Generated by Django 4.2 on 2023-05-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0004_alter_cow_breed_alter_cow_color_alter_cow_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='breed',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cow',
            name='color',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='cow',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='cow',
            name='name_of_cow',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
