# Generated by Django 4.2 on 2023-05-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0005_alter_cow_breed_alter_cow_color_alter_cow_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='color',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
