# Generated by Django 4.2 on 2023-05-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0006_alter_cow_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='breed',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cow',
            name='name_of_cow',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cow',
            name='owner',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
