# Generated by Django 4.2 on 2023-05-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0007_alter_cow_breed_alter_cow_name_of_cow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='image',
            field=models.ImageField(blank=True, upload_to='cow/'),
        ),
        migrations.AlterField(
            model_name='duplicate_cow',
            name='updated_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='cow/'),
        ),
        migrations.AlterField(
            model_name='row',
            name='image',
            field=models.ImageField(default='default.png', upload_to='entrepreneur/'),
        ),
    ]
