# Generated by Django 4.2 on 2023-06-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0008_alter_cow_image_alter_duplicate_cow_updated_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicate_cow',
            name='food_consumed',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='duplicate_cow',
            name='percentage_grass',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='duplicate_cow',
            name='percentage_solid',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
